run:
	javac Main.java
	java Main /home/bandi16/Documents/projekt/projekt/kepek

clean:
	find . -type f -name '*.class' -exec rm {} \;
	clear

delhtml:
	javac HtmlFileDeleter.java
	java HtmlFileDeleter
